### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by xcloudx01** [gregbakerstl/dns_speed_test#2]
Running it gives me the following error:

```
dns_speed_test.sh: line 3: $'\r': command not found
dns_speed_test.sh: line 4: syntax error near unexpected token `$'{\r''
'ns_speed_test.sh: line 4: `get_latency() {
```

I'm using Windows 11 and just installed the linux subsystem

**Comment by Greg-2600** [comment]
I appreciate you opening this bug!

I have not used a windows system since 2006 or so, and am not familiar with the linux subsystem.  I would recommend installing a virtual machine and running this script via linux, or tracking down a tool built for your operating system.

**Comment by Greg-2600** [comment]
.
